# TCL File Generated by Component Editor 15.1
# Fri Apr 15 11:02:25 EDT 2016
# DO NOT MODIFY


# 
# egm "EGM (T. Smouter et al.)" v1.0
# Trevor Smouter and others 2016.04.15.11:02:25
# Generates Events to Test IO
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module egm
# 
set_module_property DESCRIPTION "Generates Events to Test IO"
set_module_property NAME egm
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Trevor Smouter and others"
set_module_property DISPLAY_NAME "EGM (T. Smouter et al.)"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL egm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file egm_core.vhd VHDL PATH egm_core.vhd TOP_LEVEL_FILE
add_fileset_file LogicalStep_latency_tracker.vhd VHDL PATH LogicalStep_latency_tracker.vhd
add_fileset_file LogicalStep_pulse_generator.vhd VHDL PATH LogicalStep_pulse_generator.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_egm_slave
# 
add_interface avalon_egm_slave avalon end
set_interface_property avalon_egm_slave addressUnits WORDS
set_interface_property avalon_egm_slave associatedClock clk
set_interface_property avalon_egm_slave associatedReset reset
set_interface_property avalon_egm_slave bitsPerSymbol 8
set_interface_property avalon_egm_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_egm_slave burstcountUnits WORDS
set_interface_property avalon_egm_slave explicitAddressSpan 0
set_interface_property avalon_egm_slave holdTime 0
set_interface_property avalon_egm_slave linewrapBursts false
set_interface_property avalon_egm_slave maximumPendingReadTransactions 0
set_interface_property avalon_egm_slave maximumPendingWriteTransactions 0
set_interface_property avalon_egm_slave readLatency 0
set_interface_property avalon_egm_slave readWaitTime 1
set_interface_property avalon_egm_slave setupTime 0
set_interface_property avalon_egm_slave timingUnits Cycles
set_interface_property avalon_egm_slave writeWaitTime 0
set_interface_property avalon_egm_slave ENABLED true
set_interface_property avalon_egm_slave EXPORT_OF ""
set_interface_property avalon_egm_slave PORT_NAME_MAP ""
set_interface_property avalon_egm_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_egm_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_egm_slave chipselect chipselect Input 1
add_interface_port avalon_egm_slave address address Input 3
add_interface_port avalon_egm_slave write write Input 1
add_interface_port avalon_egm_slave writedata writedata Input 32
add_interface_port avalon_egm_slave read read Input 1
add_interface_port avalon_egm_slave readdata readdata Output 32
set_interface_assignment avalon_egm_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_egm_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_egm_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_egm_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point interface
# 
add_interface interface conduit end
set_interface_property interface associatedClock clk
set_interface_property interface associatedReset ""
set_interface_property interface ENABLED true
set_interface_property interface EXPORT_OF ""
set_interface_property interface PORT_NAME_MAP ""
set_interface_property interface CMSIS_SVD_VARIABLES ""
set_interface_property interface SVD_ADDRESS_GROUP ""

add_interface_port interface STIM stimulus Output 1
add_interface_port interface RESP response Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1

